### ISSUE TITLE
Why is everything submitted as a timing?

### ISSUE THREAD

**Issue by apg** [basecamp/trashed#11]
Hi,

I'm interested in collecting the following stats, but why they are submitted as timings... with a sample rate of 0.05(?) bewilder me greatly:

```
Rack.Server.All.GC.count:59|ms|@0.05
Rack.Server.All.GC.heap_allocated_pages:1093|ms|@0.05
Rack.Server.All.GC.heap_available_slots:447947|ms|@0.05
Rack.Server.All.GC.heap_live_slots:426958|ms|@0.05
Rack.Server.All.GC.heap_marked_slots:356005|ms|@0.05
Rack.Server.All.GC.heap_sorted_length:1069|ms|@0.05
Rack.Server.All.GC.heap_tomb_pages:0|ms|@0.05
Rack.Server.All.GC.major_gc_count:9|ms|@0.05
Rack.Server.All.GC.malloc_increase_bytes:313296|ms|@0.05
Rack.Server.All.GC.malloc_increase_bytes_limit:16777216|ms|@0.05
Rack.Server.All.GC.minor_gc_count:51|ms|@0.05
Rack.Server.All.GC.old_objects:301503|ms|@0.05
Rack.Server.All.GC.total_allocated_pages:1119|ms|@0.05
Rack.Server.All.GC.total_freed_objects:1429038|ms|@0.05
```

Most of these things look like counters, with things like `heap_marked_slots` being a gauge. Is reporting at timings an oversight? bug? just the way you do things at basecamp? Any guidance here would be welcome.

**Comment by jeremy** [comment]
Hi @apg,

These all began as gauges, but the reporting rate (per request) was a bit much. I changed them to timings so StatsD aggregates them per period and we can track min/max/etc. It's a workaround for too much per-request reporting.

Scheduling gauge reporting on a separate timer thread is the way to go.

**Comment by apg** [comment]
Hi @jeremy,

Does this mean you'd be willing to take a PR that supports a separate timer thread, and moves back to gauges / counters? Or is this not something you'd not be motivated to, internally, move to? 

I know this would break existing compatibility, so it's reasonable to say no. The timing, and per request emitting is incompatible with what we're trying to do. But, the rest of trashed is exactly what we need! Thanks for a great library!

**Comment by jeremy** [comment]
@apg Certainly! In my view, that doesn't break compatibility since it'd "just" change the gauge reporting frequency from per-request to a periodic schedule.
