### ISSUE TITLE
Feature: measure Request queue

### ISSUE THREAD

**Issue by stereobooster** [basecamp/trashed#15]
The same way as newrelic does it https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples

You configure nginx (or anything else), to send header with time when request started, then you measure time between request started and time when it was actually dispatched to ruby worker/process.

**Comment by jeremy** [comment]
We'd need to give instruments access to the request env to pull this off—meaning an API change—but it'd be straightforward from there:
```ruby
class ProxyQueueTime
  def start(state, timings, gauges, env)
    timings[:proxy_queue_time] = Time.now.to_f - parse_time(env['HTTP_WHATEVER_HEADER'])
  end
end

Trashed::ResourceUsage.instrument ProxyQueueTime.new
```
Give it a shot. PR welcome.
