### ISSUE TITLE
Ruby 1.9 support

### ISSUE THREAD

**Issue by tsevan** [basecamp/trashed#19]
I happened to try to use `trashed` with Ruby 1.9.3.

However when I try to start console with my Rails application I see the following error:
```
gems/trashed-3.2.7/lib/trashed/instruments/ruby_gc.rb:15:in `stat': non-hash given (TypeError)
gems/trashed-3.2.7/lib/trashed/instruments/ruby_gc.rb:15:in `<class:RubyGC>'
gems/trashed-3.2.7/lib/trashed/instruments/ruby_gc.rb:3:in `<module:Instruments>'
gems/trashed-3.2.7/lib/trashed/instruments/ruby_gc.rb:2:in `<module:Trashed>'
gems/trashed-3.2.7/lib/trashed/instruments/ruby_gc.rb:1:in `<top (required)>'
```

The reason is that `GC.stat` output was very basic in Ruby 1.9: https://ruby-doc.org/core-1.9.3/GC.html#method-c-stat.

Example:
```
irb(main):001:0> GC.stat
=> {:count=>19, :heap_used=>138, :heap_length=>138, :heap_increment=>0, :heap_live_num=>25491, :heap_free_num=>30907, :heap_final_num=>18}
irb(main):002:0> GC.stat :total_allocated_objects
TypeError: non-hash given
	from (irb):2:in `stat'
	from (irb):2
```

However it was extended to the modern state in Ruby 2.x: https://ruby-doc.org/core-2.1.0/GC.html#method-c-stat.

Could it be fixed?

**Comment by jeremy** [comment]
Sure. Up for doing a pull request?

We're only calling this to detect Ruby 2.1 vs 2.2 GC.stat naming changes. So we can rescue TypeError and treat that as Ruby 1.9/2.0. See here: https://github.com/basecamp/trashed/blob/291caa5dd43712de1090eaa1d112fd0e0f6c6940/lib/trashed/instruments/ruby_gc.rb#L13-L15

**Comment by tsevan** [comment]
> Up for doing a pull request?

Sure, here you go: https://github.com/basecamp/trashed/pull/20/files.

I've kept the relevant meters and fixed the profiles specs in that PR.
